### ISSUE TITLE
Handsondatatable suggestion....

### ISSUE THREAD

**Issue by seandavi** [NCBI-Hackathons/Metadata_categorization#1]
Haven't used it, but looks interesting.

http://handsontable.com/

**Comment by eweitz** [comment]
Interesting indeed!  Thanks for putting this on our radar, @seandavi.

See also: https://github.com/handsontable/handsontable.  Handsontable is free and open source.

@FullyWashable, @DCGenomics, as noted in yesterday's demo, this application currently uses the DataTables library (http://www.datatables.net/, https://github.com/DataTables/DataTables).  By default it supports reading, but not editing.  Editing DataTables is possible with a paid plug-in, https://editor.datatables.net/.  

Handsontable offers such table editing functionality out-of-the-box for free.  Editing is an essential but currently unimplemented feature of our application.  Given that, I will see what I can do over the next few days to prototype a new Metadata Categorization user interface with Handsontable.

**Comment by DCGenomics** [comment]
This sounds like a good plan, thanks Eric!

**Comment by seandavi** [comment]
If you are at all interested in using R/shiny, there are at least two implementations of handsontable integration with shiny. This might be a nice way to tie backend capabilities to the UI with little work. Shiny can be run as a server, or as a simple application on any system that supports R (everything).
