### ISSUE TITLE
Add developmental stage and sex and disease to UI

### ISSUE THREAD

**Issue by DCGenomics** [NCBI-Hackathons/Metadata_categorization#13]
For both drosophila and human

**Comment by eweitz** [comment]
Done per https://github.com/NCBI-Hackathons/Metadata_categorization/commit/e1215408440d5e29a679b98e26d3dd6e3738d7a8 and https://github.com/NCBI-Hackathons/Metadata_categorization/commit/0a4ca03f3e0b43e6f39edf97f11ef6c784759ec7.
