### ISSUE TITLE
Single individual record not propagating to summary record

### ISSUE THREAD

**Issue by eweitz** [NCBI-Hackathons/Metadata_categorization#27]
In a summary record that has only 1 individual record:
1. Open the individual record dialog
2. Edit a value
3. Close the dialog
4. Note that the value entered at the individual level unexpectedly does not propagate to the summary level

**Comment by eweitz** [comment]
@FullyWashable, in case indexers ask, I aim to fix this and issue #28 over the weekend.

**Comment by FullyWashable** [comment]
You're a rockstar. Thank you.

**Comment by eweitz** [comment]
Fixed!
