### ISSUE TITLE
Disappearing biosample ids

### ISSUE THREAD

**Issue by FullyWashable** [NCBI-Hackathons/Metadata_categorization#31]
"For some records, when I go to the expanded entries ( clicking on the + sign)  the first ID number changes to “null”  after I add information and I can’t access it after that."

From Janice.

**Comment by eweitz** [comment]
Fixed.  This bug was due to me overlooking how JavaScript objects are pass-by-reference, not by-value.  [Copying by value](https://github.com/NCBI-Hackathons/Metadata_categorization/commit/c4799e4e909fdc7701b26cffebf21d15a8348635#diff-189295a0b77f4ed2fbaa4e2d3d083c36R160) solved the problem.
